### PR TITLE
Added group and host variables and optimized tasks.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by franklinkim** [comment]
hi, do you have an example usage for this?

What I think you're trying to do is to add sth to the `files` hash from your `group_vars` and `host_vars` right? sth like:

```
# vars/foo.yml
files:
 - path: /foo/bar

# group_vars/foo.yml
files_goup:
 - path: /foo/bar/group

# host_vars/foo.yml
files_host:
 - path: /foo/bar/host
```

and you would like to have:

```
files:
 - path: /foo/bar
 - path: /foo/bar/group
 - path: /foo/bar/host
```

If you're looking for this, it might be better to use sth like:

```
- hosts: all
  sudo: yes
  roles:
    - { role: franklinkim.files, files: files }
    - { role: franklinkim.files, files: files_group }
    - { role: franklinkim.files, files: files_host }
```

or take a look at the `ansible.cfg` and the `hash_behavior`. this is probably more to your liking:

http://docs.ansible.com/ansible/intro_configuration.html#hash-behaviour

**Comment by ypid** [comment]
Running the role multiple times is a good idea for such a simple role but I guess it would not hurt to add two more variables? I like this approach also practiced by http://debops.org/. I know the `hash_behavior` but you don’t want to change that as it has too many side effects (what if you want to override it for one host?).
Also it would have no effect in this case:

> it does not affect variables whose values are scalars (integers, strings) or arrays. We generally recommend not using this setting unless you think you have an absolute need for it

**Comment by franklinkim** [comment]
Debops is a framework which has it's conventions. I'm trying to keep my roles as simple and clean as possible. Could you provide an example on how you are using it for better understanding and the Readme file?

Another way would be to add the merging as a `pre_task`:

``` yaml
- hosts: all
  sudo: yes
  pre_tasks:
    - name: Combine file lists
      set_fact:
        cron_tasks: "{{ cron_tasks + cron_group_tasks + cron_host_tasks | default([]) }}"
```

**Comment by ypid** [comment]
Could be done with a pre task of course. On the other hand, I really don’t think that it makes the role more complicated. I do stuff like changing permissions of files/directories replacing files with symlinks and so on. I is just handy to define this in the inventory. Maybe to clarify my use case for Ansible. I use it mainly to manage workstations, home servers and some projects at work like setting up ownCloud or managing school networks. When you operate big data centers then things probably look different.
I think the usage will become clear once one needs it. Not sure if it worth adding this to the readme.

**Comment by franklinkim** [comment]
It's not making it too complicated but it adds sth that's not really necessary and can be handled with different approaches. In your case I would suggest defining the `files` variable inside your playbook i.e.

``` ini
[all]
trusty ansible_ssh_host=192.168.33.99 ansible_ssh_user=vagrant ansible_ssh_private_key_file=/Users/.../.vagrant.d/insecure_private_key

[all:vars]
files_list=["one", "two"]

[trusty]
trusty

[trusty:vars]
files_host_list=["three", "four"]

[group1]
trusty

[group1:vars]
files_group_list=["five", "six"]
```

``` yaml
- hosts: all
  sudo: yes
  vars:
    files: "{{ files_group_list + files_host_list + files_list }}"
  tasks:
    - debug: var=files_list
    - debug: var=files_host_list
    - debug: var=files_group_list
    - debug: var=files
```

or of cause, keep your clone of this repository.

_I leave this open for voting and if more people want this to be included I'll also check all my other roles to be sync with this feature._

**Comment by ypid** [comment]
Fair enough. I will just use my fork of it for now.

**Pull request closed without merging**
